name: release

on:
  push:
    tags: ["v[0-9]*"]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref_name }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-tarball-linux:
    name: build-tarball-${{matrix.name}}
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x64
            target: x86_64-unknown-linux-gnu
          - name: linux-x64-musl
            target: x86_64-unknown-linux-musl
          - name: linux-arm64
            target: aarch64-unknown-linux-gnu
          - name: linux-arm64-musl
            target: aarch64-unknown-linux-musl
          - name: linux-armv7
            target: armv7-unknown-linux-gnueabi
          - name: linux-armv7-musl
            target: armv7-unknown-linux-musleabi
    steps:
      - uses: actions/checkout@v4
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: cache crates
        id: cache-crates
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry/cache
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-registry
      - name: build-tarball ${{matrix.target}}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 45
          max_attempts: 3
          command: scripts/build-tarball.sh ${{matrix.target}}
      - uses: actions/upload-artifact@v4
        with:
          name: tarball-${{matrix.target}}
          path: |
            dist/mise-*.tar.xz
            dist/mise-*.tar.gz
            dist/mise-*.tar.zst
          if-no-files-found: error

  build-tarball-macos:
    name: build-tarball-${{matrix.name}}
    runs-on: macos-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macos-x64
            target: x86_64-apple-darwin
          - name: macos-arm64
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: cache crates
        id: cache-crates
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry/cache
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-registry
      - name: Setup Rust target
        run: rustup target add ${{matrix.target}}
      - name: build-tarball ${{matrix.target}}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 90
          max_attempts: 3
          command: scripts/build-tarball.sh ${{matrix.target}}
      - uses: actions/upload-artifact@v4
        with:
          name: tarball-${{matrix.target}}
          path: |
            dist/mise-*.tar.xz
            dist/mise-*.tar.gz
            dist/mise-*.tar.zst
          if-no-files-found: error

  build-tarball-windows:
    name: build-tarball-windows-${{matrix.arch}}
    runs-on: windows-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            target: aarch64-pc-windows-msvc
          - arch: x64
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add ${{matrix.target}}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{matrix.arch}}
      - run: scripts/build-tarball.ps1 ${{matrix.target}}
        env:
          OS: windows
          ARCH: ${{matrix.arch}}
      - uses: actions/upload-artifact@v4
        with:
          name: tarball-${{matrix.target}}
          path: dist/*.zip
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    needs:
      - build-tarball-linux
      - build-tarball-macos
      - build-tarball-windows
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: tarball-*
          merge-multiple: true
      - name: Create GitHub Release
        run: |
          VERSION="$(./scripts/get-version.sh)"
          gh release create "$VERSION" \
            --title "$VERSION" \
            --generate-notes \
            artifacts/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
